### ISSUE TITLE
Missing shared libraries in Windows package cause issues in downstream packages

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/libssh2-feedstock#14]
Prior to #11 no shared libraries were included in the Windows packages but now these libraries are included.  This will cause issues if a package, for example curl, is built against the shared library but is installed in an environment with a version of the libssh2 package lacking the shared library.  This is occurring in conda-forge/ca-certificates-feedstock#27.

Moving the pre-shared library builds to a `broken` label should fix this issue.

**Comment by ocefpaf** [comment]
> Moving the pre-shared library builds to a broken label should fix this issue.

I'm guessing those are the Windows builds 0 and 1 for `libssh2 1.8.0`, right?
I'll experiment moving those and re-start the CIs.

**Comment by ocefpaf** [comment]
It works :tada: 

See https://github.com/conda-forge/ca-certificates-feedstock/pull/27

**Comment by jjhelmus** [comment]
Excellent, thanks for help @ocefpaf.

**Comment by ocefpaf** [comment]
Thanks for figuring it would! This actually fixed two other builds I have that were failing and I had no idea what was going on!
