### ISSUE TITLE
Wrong initial build number for version 1.8.0

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/libssh2-feedstock#5]
When upgrading to version 1.8.0, I forgot to reset the build number. What is the recommended course of action?

**Comment by jakirkham** [comment]
Nothing. Basically you leave it alone until the next version and reset it then.

**Comment by shadowwalkersb** [comment]
Cool. I'll leave it alone. Hope it doesn't cause confusion. Then, I am closing the PR #6 .
